name: sonn-core
version: 0.1.1
slug: sonn-core
description: Loxone Music Server emulation powered by sonn-audio/core
url: https://sonn-audio.github.io/docs/
arch:
  - amd64
  - aarch64
startup: application
boot: auto
host_network: true
init: false
webui: http://[HOST]:[PORT:7090]
map:
  - type: addon_config
    read_only: false
    path: /app/data
